// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK9_DS4pq1U6Ku2TjJ_waWOVkQ7bNmlWQ',
    appId: '1:302291043771:web:07ff16e2844bf63b7cb09e',
    messagingSenderId: '302291043771',
    projectId: 'crud-95924',
    authDomain: 'crud-95924.firebaseapp.com',
    storageBucket: 'crud-95924.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-3G29Dz7_kYfjwqRteVSy6dR-tHDMRKI',
    appId: '1:302291043771:android:fef9cb896e7e638e7cb09e',
    messagingSenderId: '302291043771',
    projectId: 'crud-95924',
    storageBucket: 'crud-95924.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB5ioZZpJiWNXfYv-ycHTzIOc4DuObjfI',
    appId: '1:302291043771:ios:d1e8b8ebd8ee0ce37cb09e',
    messagingSenderId: '302291043771',
    projectId: 'crud-95924',
    storageBucket: 'crud-95924.appspot.com',
    androidClientId: '302291043771-otvsjs9jrgt50mstnemqtipbcp1k0577.apps.googleusercontent.com',
    iosClientId: '302291043771-nt35dbvvs7bt4ebd290qufpofmjsr7uc.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB5ioZZpJiWNXfYv-ycHTzIOc4DuObjfI',
    appId: '1:302291043771:ios:d1e8b8ebd8ee0ce37cb09e',
    messagingSenderId: '302291043771',
    projectId: 'crud-95924',
    storageBucket: 'crud-95924.appspot.com',
    androidClientId: '302291043771-otvsjs9jrgt50mstnemqtipbcp1k0577.apps.googleusercontent.com',
    iosClientId: '302291043771-nt35dbvvs7bt4ebd290qufpofmjsr7uc.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );
}
